services:
  starboard:
    build: .
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./cmd/starboard/config.json:/app/config.json

  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=starboard
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 5
volumes:
  pgdata:
